const popularFilms = [
    {
        id: '1',
        name: 'Inception',
        category: ['Sci - Fi', 'Action'],
        releaseYear: 2010,
        country: 'USA',
        director: 'Christopher Nolan',
        actors: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Ellen Page'],
        poster: 'https://webserver-l2tp.onrender.com/files/images/inception.jpg',
        views: 10,
        rate: 4.5,
        linkFilm:
            'https://drive.google.com/file/d/1i8ZZahNukxku7rMBwPsk_3FUKnmVDDjX/preview',
    },
    {
        id: '2',
        name: 'The Social Network',
        category: ['Drama', 'Thriller'],
        releaseYear: 2010,
        country: 'USA',
        director: 'David Fincher',
        actors: ['Jesse Eisenberg', 'Andrew Garfield', 'Justin Timberlake'],
        poster: 'https://webserver-l2tp.onrender.com/files/images/the-social-network.jpg',
        views: 12,
        rate: 3.9,
        linkFilm:
            'https://drive.google.com/file/d/1i8ZZahNukxku7rMBwPsk_3FUKnmVDDjX/preview',
    },
    {
        id: '3',
        name: 'Toy Story 3',
        category: ['Animation', 'Family'],
        releaseYear: 2010,
        country: 'USA',
        director: 'Lee Unkrich',
        actors: ['Tom Hanks', 'Tim Allen', 'Joan Cusack'],
        poster: 'https://webserver-l2tp.onrender.com/files/images/toy-story-3.jpg',
        views: 13,
        rate: 4.15,
        linkFilm:
            'https://drive.google.com/file/d/1i8ZZahNukxku7rMBwPsk_3FUKnmVDDjX/preview',
    },
    {
        id: '4',
        name: "The King's Speech",
        category: ['History', 'Drama'],
        releaseYear: 2010,
        country: 'UK',
        director: 'Tom Hooper',
        actors: ['Colin Firth', 'Geoffrey Rush', 'Helena Bonham Carter'],
        poster: 'https://webserver-l2tp.onrender.com/files/images/the-kings-speech.jpg',
        views: 10,
        rate: 4,
        linkFilm:
            'https://drive.google.com/file/d/1i8ZZahNukxku7rMBwPsk_3FUKnmVDDjX/preview',
    },
    {
        id: '5',
        name: 'Black Swan',
        category: ['Drama', 'Horror'],
        releaseYear: 2010,
        country: 'USA',
        director: 'Darren Aronofsky',
        actors: ['Natalie Portman', 'Mila Kunis', 'Vincent Cassel'],
        poster: 'https://webserver-l2tp.onrender.com/files/images/black-swan.jpg',
        views: 10,
        rate: 4,
        linkFilm:
            'https://drive.google.com/file/d/1i8ZZahNukxku7rMBwPsk_3FUKnmVDDjX/preview',
    },
    {
        id: '6',
        name: 'The Help',
        category: ['Drama'],
        releaseYear: 2011,
        country: 'USA',
        director: 'Tate Taylor',
        actors: ['Emma Stone', 'Viola Davis', 'Octavia Spencer'],
        poster: 'https://webserver-l2tp.onrender.com/files/images/the-help.jpg',
        views: 10,
        rate: 4.05,
        linkFilm:
            'https://drive.google.com/file/d/1i8ZZahNukxku7rMBwPsk_3FUKnmVDDjX/preview',
    },
    {
        id: '7',
        name: 'Mad Max: Fury Road',
        category: ['Action', 'Sci-Fi'],
        releaseYear: 2015,
        country: 'Australia',
        director: 'George Miller',
        actors: ['Charlize Theron', 'Tom Hardy', 'Nicholas Hoult'],
        poster: 'https://webserver-l2tp.onrender.com/files/images/mad-max-fury-road.jpg',
        views: 10,
        rate: 4.25,
        linkFilm:
            'https://drive.google.com/file/d/1i8ZZahNukxku7rMBwPsk_3FUKnmVDDjX/preview',
    },
    {
        id: '8',
        name: 'Parasite',
        category: ['Drama', 'Horror'],
        releaseYear: 2019,
        country: 'South Korea',
        director: 'Bong Joon-ho',
        actors: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong'],
        poster: 'https://webserver-l2tp.onrender.com/files/images/parasite.jpg',
        views: 10,
        rate: 4.4,
        linkFilm:
            'https://drive.google.com/file/d/1i8ZZahNukxku7rMBwPsk_3FUKnmVDDjX/preview',
    },
    {
        id: '9',
        name: 'The Grand Budapest Hotel',
        category: ['Comedy', 'Drama'],
        releaseYear: 2014,
        country: 'USA',
        director: 'Wes Anderson',
        actors: ['Ralph Fiennes', 'F. Murray Abraham', 'Mathieu Amalric'],
        poster: 'https://webserver-l2tp.onrender.com/files/images/the-grand-budapest-hotel.jpg',
        views: 10,
        rate: 4.05,
        linkFilm:
            'https://drive.google.com/file/d/1i8ZZahNukxku7rMBwPsk_3FUKnmVDDjX/preview',
    },
    {
        id: '10',
        name: 'Iron Man',
        category: ['Action', 'Adventure'],
        releaseYear: 2008,
        country: 'USA',
        director: 'Jon Favreau',
        actors: ['Robert Downey Jr.', 'Gwyneth Paltrow', 'Jeff Bridges'],
        poster: 'https://webserver-l2tp.onrender.com/files/images/iron-man.jpg',
        views: 10,
        rate: 3.95,
        linkFilm:
            'https://drive.google.com/file/d/1i8ZZahNukxku7rMBwPsk_3FUKnmVDDjX/preview',
    },
];

export default popularFilms;
